### ISSUE TITLE
Feedback on your presentation

### ISSUE THREAD

**Issue by jchoi2022** [KAIST-IS521/2018s-presentation-team5#10]
Thank you for your efforts in the activity. Here are some feedback gathered from all the TAs and professor. You can close this issue when the feedback is well delivered to all the members.

- In overall, introduction about yourselves was appealing, but presentation about your development environment could have been more intriguing.
- Slide had a good and consistent style.
- It was a good idea to include contacts in the slide. 
- Thank you for mentioning the TA at the start.
- Some images used in the slide seem to need external sources.
- For Junghwan, time limit was slightly exceeded (3 min 26 sec). Also, try to relax a little bit and make some more eye contact with audiences. Except for that, it was a good presentation.
- For Kyuchan, some of the photos were too small that audiences could not recognize their content. Also, some last slides passed too quickly.
- For Hojoon, 'What I Use' part may be improved to be more attractive to audiences.
- Your presentation time was as follow.
  + Junghwan : 3min 26sec
  + Kyuchan : 2min 56sec
  + Hojoon : 2min 55sec
  + Total : 10min 52sec

**Comment by AhnMo** [comment]
Thank you for your comment.
When I practice the PT first, there is more over time limit.
So, I make it shorter by skipping the content, but that is not enough :(
Anyway I need to keep practice the presentation for better.
Thanks again for your hard work!

**Comment by sangkilc** [comment]
@jchoi2022 Thank you for creating this issue. I think you'd better put the presentation time for each member in your summary.

**Comment by jchoi2022** [comment]
I updated the comment, thank you!
